b1 = set(map(str, input("Введите через запятую книги, прочитанные первым учеником: ").split(", ")))
b2 = set(map(str, input("Введите через запятую книги, прочитанные вторым учеником: ").split(", ")))
b3 = b1.intersection(b2)
print(b3)
print(len(b3))