n_num = int(input("Введите число: "))
n_str = str(n_num)
print(f"0 – {n_str.count('0', 0, len(n_str))}")
print(f"1 – {n_str.count('1', 0, len(n_str))}")
print(f"2 – {n_str.count('2', 0, len(n_str))}")
print(f"3 – {n_str.count('3', 0, len(n_str))}")
print(f"4 – {n_str.count('4', 0, len(n_str))}")
print(f"5 – {n_str.count('5', 0, len(n_str))}")
print(f"6 – {n_str.count('6', 0, len(n_str))}")
print(f"7 – {n_str.count('7', 0, len(n_str))}")
print(f"8 – {n_str.count('8', 0, len(n_str))}")
print(f"9 – {n_str.count('9', 0, len(n_str))}")
